-- ADMIN USER
INSERT INTO auth.users (
        id,
        instance_id,
        aud,
        role,
        email,
        encrypted_password,
        email_confirmed_at,
        invited_at,
        confirmation_token,
        confirmation_sent_at,
        recovery_token,
        recovery_sent_at,
        email_change_token_new,
        email_change,
        email_change_sent_at,
        last_sign_in_at,
        raw_app_meta_data,
        raw_user_meta_data,
        is_super_admin,
        created_at,
        updated_at,
        phone,
        phone_confirmed_at,
        phone_change,
        phone_change_token,
        phone_change_sent_at,
        email_change_token_current,
        email_change_confirm_status,
        banned_until,
        reauthentication_token,
        reauthentication_sent_at
    )
VALUES (
    '11111111-1111-1111-1111-111111111111'::uuid,
    '00000000-0000-0000-0000-000000000000'::uuid,
    'authenticated',
    'authenticated',
    'nuchat-admin@yopmail.com',
    crypt('admin', gen_salt('bf')),
    now(),
    NULL::timestamp,
    '',
    NULL::timestamp,
    '',
    NULL::timestamp,
    '',
    '',
    NULL::timestamp,
    now()::timestamp,
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{}'::jsonb,
    0::boolean,
    '2023-05-05 03:41:27.391146+00'::timestamp,
    '2023-05-05 03:41:27.391146+00'::timestamp,
    NULL,
    NULL::timestamp,
    '',
    '',
    NULL::timestamp,
    '',
    0,
    NULL::timestamp,
    '',
    NULL::timestamp
);

UPDATE public.profiles SET username = 'admin', full_name = 'admin', role = 'admin' WHERE id = '11111111-1111-1111-1111-111111111111'::uuid;
