version: "3.8"

services:
  studio:
    build:
      context: ..
      dockerfile: studio/Dockerfile
      target: dev
    ports:
      - 8082:8082
  mail:
    container_name: supabase-mail
    image: inbucket/inbucket:3.0.3
    ports:
      - "2500:2500" # SMTP
      - "9000:9000" # web interface
      - "1100:1100" # POP3
  auth:
    environment:
      - GOTRUE_SMTP_USER=${SMTP_USER}
      - GOTRUE_SMTP_PASS=${SMTP_PASS}
      - GOTRUE_EXTERNAL_GITHUB_ENABLED=${GOTRUE_EXTERNAL_GITHUB_ENABLED}
      - GOTRUE_EXTERNAL_GITHUB_CLIENT_ID=${GOTRUE_EXTERNAL_GITHUB_CLIENT_ID}
      - GOTRUE_EXTERNAL_GITHUB_SECRET=${GOTRUE_EXTERNAL_GITHUB_SECRET}
      - GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI=${GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI}
  meta:
    ports:
      - 5555:8080
  db:
    restart: no
    volumes:
      # Always use a fresh database when developing
      - /var/lib/postgresql/data # ./volumes/db/data:
      # Seed data should be inserted last (alphabetical order)
      - ./dev/01-seed-admin-user.sql:/docker-entrypoint-initdb.d/seed1.sql
      - ./dev/02-seed-normal-users.sql:/docker-entrypoint-initdb.d/seed2.sql
      - ./dev/03-seed-normal-users-profile.sql:/docker-entrypoint-initdb.d/seed3.sql
  storage:
    volumes:
      - /var/lib/storage # ./volumes/storage:
