name: Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd ~/nuchat
          git pull origin main
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh 
          npm ci
          npm run prod
